name: "test"
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: base
        restart: unless-stopped
        tty: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/docker-extended.ini
        networks:
            - app-network
        depends_on:
            - db

    #Nginx Service
    webserver:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - app-network
        depends_on:
            - app

    #MySQL Service
    db:
        image: mysql:8.0
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            "MYSQL_DATABASE": "app"
            "MYSQL_USER": "app"
            "MYSQL_PASSWORD": "password"
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes"
        volumes:
            #      - ./docker/mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/extend.cnf
            - db-data:/var/lib/mysql
        networks:
            - app-network

    utility:
        profiles:
            - optional
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: dev
        restart: unless-stopped
        tty: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/docker-extended.ini
        networks:
            - app-network
        depends_on:
            - db

    vapor:
        profiles:
            - optional
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: vapor
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/docker-extended.ini
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - app-network
        depends_on:
            - db

networks:
    app-network:
        driver: bridge

volumes:
    db-data:
        driver: local
